#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 4
final_space = true

[upgrade]
source = 'cdn'
interval = '168h'
auto = false
notice = false

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = "os"
style = "powerline"
# powerline_symbol = ""
# leading_powerline_symbol = ""
foreground = "transparent"
background = "#bb9af7"
template = ' {{ .Icon }} '

[[blocks.segments]]
type = "session"
style = "diamond"
leading_diamond = ""
trailing_diamond = ""
foreground = "transparent"
background = "#bb9af7"
template = "{{ .UserName }}"


[[blocks.segments]]
type = 'path'
style = 'powerline'
powerline_symbol = ""
foreground = 'transparent'
background = 'blue'
template = '{{ .Path }}'

[blocks.segments.properties]
style = 'full'

[[blocks.segments]]
type = "git"
style = "powerline"
powerline_symbol = ""
foreground = "black"
background = "#9ece6a"
background_templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}#ff9e64{{ end }}",
    "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}",
    "{{ if gt .Ahead 0 }}#B388FF{{ end }}",
    "{{ if gt .Behind 0 }}#B388FB{{ end }}",
]
template = " {{ .HEAD }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "

[blocks.segments.options]
fetch_status = true
fetch_upstream_icon = false
display_status = true
branch_icon = ''
# source = "cli"

[[blocks]]
type = 'rprompt'
overflow = 'hidden'

[[blocks.segments]]
type = 'python'
style = 'powerline'
display_mode = 'environment'
foreground = 'magenta'
background = 'transparent'
template = '{{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}  '

[[blocks.segments]]
type = 'executiontime'
style = 'plain'
foreground = 'yellow'
background = 'transparent'
template = '{{ .FormattedMs }}'

[blocks.segments.properties]
threshold = 5000

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'plain'
foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
]
background = 'transparent'
template = '❯'

[transient_prompt]
foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
]
background = 'transparent'
template = '❯ '

[secondary_prompt]
foreground = 'magenta'
background = 'transparent'
template = '❯❯ '
